### ISSUE TITLE
Add jq command on README Requirements

### ISSUE THREAD

**Issue by RicoToothless** [getamis/vishwakarma#104]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature request

**What happened**:
Error message
`
'go run main.go -key $PKCS_KEY  | jq '.keys += [.keys[0]] | .keys[1].kid = ""' >  ./examples/iam-auth-and-irsa/k8s-cluster/.secret/keys.json': exit status 127. Output: /bin/sh: jq: command not found
`

**What you expected to happen**:
Add `jq` command on README Requirements 

**How to reproduce it (as minimally and precisely as possible)**:
`terraform apply -target=module.irsa` without jq installed

**Anything else we need to know?**:
I can help this issue 👋

**Comment by smalltown** [comment]
thank you!!
