### ISSUE TITLE
ASG Name tags duplicated on modules/aws/kube-worker when give Name tag from extra_tags

### ISSUE THREAD

**Issue by soem** [getamis/vishwakarma#108]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug report

**What happened**:
```
          + {
              + "key"                 = "Name"
              + "propagate_at_launch" = "true"
              + "value"               = "test-getamis-k8s"
            },
          + {
              + "key"                 = "Name"
              + "propagate_at_launch" = "true"
              + "value"               = "test-getamis-k8s-worker-spot"
            },
```

**What you expected to happen**:
Not to use the `Name` tag from `extra_tags`, set `Name` tag by module **name** variable.
Just like the `modules/aws/kube-etcd`:
https://github.com/getamis/vishwakarma/blob/0631034cfabded5a18b90861a3bc87de787012bf/modules/aws/kube-etcd/main.tf#L78-L82

**How to reproduce it (as minimally and precisely as possible)**:
Launch example cluster:
https://github.com/getamis/vishwakarma/tree/master/examples/kubernetes-cluster

**Anything else we need to know?**:
Fix in PR: https://github.com/getamis/vishwakarma/pull/111

**Comment by smalltown** [comment]
Thank for your help
