### ISSUE TITLE
The irsa s3_object always have to be updated

### ISSUE THREAD

**Issue by soem** [getamis/vishwakarma#109]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature request

**What happened**:
The `module.irsa.aws_s3_bucket_object.keys_json` always have to be updated, since `keys_json` is reading from file data source.
```
Terraform will perform the following actions:

  # module.irsa.data.local_file.keys_json will be read during apply
  # (config refers to values not yet known)
 <= data "local_file" "keys_json"  {
 ...

  # module.irsa.aws_s3_bucket_object.keys_json will be updated in-place
  ~ resource "aws_s3_bucket_object" "keys_json" {
  ...
```

According to the data source document, it might be caused by data resource won't be checked before apply phase.
https://www.terraform.io/docs/language/data-sources/index.html#data-resource-dependencies
```
NOTE: In Terraform 0.12 and earlier, due to the data resource behavior of deferring the read until the apply phase when depending on values that are not yet known...
```

**What you expected to happen**:
The S3 object only have to be updated when necessary.

**How to reproduce it (as minimally and precisely as possible)**:
Launch example cluster:
https://github.com/getamis/vishwakarma/tree/master/examples/kubernetes-cluster

Then, apply the module.master many times.
```
terraform apply -target=module.master
```

**Anything else we need to know?**:
I've wrote a mitigation PR for this issue: https://github.com/getamis/vishwakarma/pull/110

**Comment by smalltown** [comment]
Thank for your help
