### ISSUE TITLE
upgrade k8s cluster

### ISSUE THREAD

**Issue by shankar-bala** [getamis/vishwakarma#22]
Hi

Deployment of cluster using image quay.io/coreos/hyperkube with version v1.10.5 works well..as soon as we change it to use k8s.gcr.io/hyperkube:v1.10.11 on all the components (worker, master etc..) , cluster broke ..we see etcd running , but api server is not getting started

is this a known issue ?? or what's the procedure in case to upgrade the existing k8s version ?/

thanks
shan

**Comment by alanchchen** [comment]
Hi, not sure about your problem, do you have logs for kubelet or the API server?

BTW, Since `quay.io/coreos/hyperkube` is deprecated (see [here](https://github.com/coreos/bugs/issues/2470)), we're migrating to official docker image.

**Comment by shankar-bala** [comment]
Hi

I have fixed the problem..after moving to k8s 1.11.x using gcr.io repo., rkt was not pulling images..have to change it to use "docker://<imageurl>:<tag>" ., it worked..

SHan
